More translate
shortthu/osu-web pull request #17
Opened 2018-04-16 10:19 UTC by shortthu

¯\_(ツ)_/¯

2018-04-17 15:09 UTC, adv3006 requested changes
Fix this and this is good to go

2018-04-17 15:09 UTC, adv3006 commented on resources/lang/vi/password_reset.php
> +        'missing_key' => 'Cần thiết.',
Dịch là *bắt buộc*

2018-04-17 15:09 UTC, adv3006 commented on resources/lang/vi/password_reset.php
> +        'user_not_found' => 'Người dùng đã yêu cầu không tồn tại.',
Nghe luộm thuộm quá
Chỉ cần dịch là 'người dùng này không tồn tại' là dc rồi

2018-04-17 15:09 UTC, adv3006 commented on resources/lang/vi/password_reset.php
> +        'too_many_tries' => 'Quá nhiều nỗ lực không thành công.',
Từ 'nỗ lực' nghe nó cao quá. Plz đổi

2018-04-17 15:09 UTC, adv3006 commented on resources/lang/vi/status_page.php
> +        'score' => 'Số Điểm Được Gửi trên Giây',
đổi từ `trên` vì nghe rất giống máy dịch

2018-04-17 15:35 UTC, shortthu commented on resources/lang/vi/status_page.php
> +        'score' => 'Số Điểm Được Gửi trên Giây',
~~thật ra máy dịch là `mỗi`~~

2018-04-19 15:14 UTC, adv3006 approved these changes
Seems good now

2018-04-19 15:14 UTC, merged