The rest
shortthu/osu-web pull request #19
Opened 2018-05-05 14:19 UTC by shortthu

:dab:

2018-05-06 05:08 UTC, adv3006 requested changes
plz fix

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/store.php
> +        'delayed_shipping' => 'Chúng tôi hiện đang bị choáng ngợp bởi các đơn hàng! Bạn vẫn có thể thoải mái đặt hàng, nhưng vui lòng đợi **thêm 1-2 tuần** trong khi chúng tôi bắt kịp với những đơn h
đổi từ `choáng ngợp`  bằng từ khác nghe cho ổn hơn

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/store.php
> +        'notify' => 'Thông báo cho tôi khi có sẵn!',
`khi có hàng`

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/model_validation.php
> +        'weak' => 'Mật khẩu có trong danh sách đen.', //???
dịch là mật khẩu `yếu` hay tương tự
Blacklist (mật khẩu) ở đây là list mấy cái mật khẩu dễ đoán ra hay mò ra đc như zxc123, 123456, etc.

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/model_validation.php
> +        'invalid_beatmap_id' => 'Difficulty đã chỉ định không hợp lệ.',
dịch specified thành `được chọn` để nghe cho neutral 1 chút

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/model_validation.php
> +        'invalid_beatmapset_id' => 'Beatmap đã chỉ định không hợp lệ.',
^

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/model_validation.php
> +            'owner' => 'Không hype map của bạn.',
`Không thể hype` để đọc nó bớt cộc lốc

2018-05-06 05:08 UTC, adv3006 commented on resources/lang/vi/model_validation.php
> +            'exceeds_beatmapset_length' => 'Mốc thời gian đã chỉ định vượt quá độ dài beatmap.',
dịch specified thành `được chọn` để nghe cho neutral 1 chút

2018-05-06 14:16 UTC, shortthu commented on resources/lang/vi/store.php
> +        'delayed_shipping' => 'Chúng tôi hiện đang bị choáng ngợp bởi các đơn hàng! Bạn vẫn có thể thoải mái đặt hàng, nhưng vui lòng đợi **thêm 1-2 tuần** trong khi chúng tôi bắt kịp với những đơn h
~~choáng ngợp cho vui~~ what should  I use

2018-05-06 14:22 UTC, tetsureign commented on resources/lang/vi/model_validation.php
> +            'owner' => 'Không hype map của bạn.',
Thật ra nó đã cộc lốc từ bản gốc rồi =)))

2018-05-07 01:39 UTC, adv3006 commented on resources/lang/vi/store.php
> +        'delayed_shipping' => 'Chúng tôi hiện đang bị choáng ngợp bởi các đơn hàng! Bạn vẫn có thể thoải mái đặt hàng, nhưng vui lòng đợi **thêm 1-2 tuần** trong khi chúng tôi bắt kịp với những đơn h
Nếu thấy khó dịch thì cứ rephrase + dịch thoáng 1 chút miễn vẫn giữ đc tính neutral là đc.
Like this:
`Hiện tại chúng tôi đang có một lượng đơn hàng rất lớn!...`

2018-05-07 02:27 UTC, adv3006 commented
okay

2018-05-07 02:27 UTC, adv3006 approved these changes

2018-05-07 02:33 UTC, merged