vn-ized
shortthu/osu-web pull request #2
Opened 2017-12-22 07:46 UTC by AcmeDVoid

2017-12-22 07:48 UTC, shortthu commented on resources/lang/vi/admin.php
> +                'no-cover' => 'No cover set',  // No cover set
ủa sao chỗ này chưa trans :)))

2017-12-22 07:50 UTC, AcmeDVoid commented on resources/lang/vi/admin.php
> +                'no-cover' => 'No cover set',  // No cover set
ayy

2017-12-22 07:59 UTC, shortthu commented on resources/lang/vi/admin.php
> +            'title' => 'Đồ chơi điều khiển của Admin',  // Admin Console Thingy
🤔 
btw cái này caps hết mà

2017-12-22 07:59 UTC, shortthu commented on resources/lang/vi/admin.php
> +                'title' => 'Danh sách bìa của Forum',  //Forum Covers List
all caps

2017-12-22 08:00 UTC, shortthu commented on resources/lang/vi/admin.php
> +                    'update' => 'Cập nhật',  // Update
cái này có cần caps hết cả hai chữ `cập nhật` không nhỉ 🤔

2017-12-22 08:02 UTC, shortthu commented on resources/lang/vi/model_validation/fulfillments.php
> +        'insufficient_paid' => 'Không đủ tiền đổi tên tài khoản(:expected > :actual)', // Username change cost exceeds amount paid (:expected > :actual)
`Không đủ`? https://puu.sh/yLEXY/b8dae886fb.png

2017-12-22 08:03 UTC, shortthu commented on resources/lang/vi/admin.php
> +                    'update' => 'Cập nhật',  // Update
let's caps all of them

2017-12-22 08:04 UTC, shortthu commented on resources/lang/vi/model_validation/fulfillments.php
> +        'only_one' => 'Bạn chỉ cho đổi tên tài khoản 1 lần cho mỗi đơn đặt hàng', //only 1 username change allowed per order fulfillment.
`Chỉ cho đổi tên tài khoản 1 lần cho mỗi đơn đặt hàng` là đủ

2017-12-22 08:08 UTC, shortthu commented on resources/lang/vi/model_validation/payments.php
> -            'virtual_only' => '`:provider` payment is not valid for physical items.',
what this string do btw lol

2017-12-22 08:13 UTC, shortthu commented on resources/lang/vi/paypal/errors.php
> +    'instrument_declined' => 'Không thể sự dụng phương thức thanh toàn trong Paypal',  // The selected payment method was rejected by Paypal.
>sự dụng

typo

2017-12-22 08:15 UTC, shortthu commented on resources/lang/vi/paypal/errors.php
> +    'unknown' => "Thanh toán đã bị từ chối, nhưng chúng tôi không biết tại sao",  // ...ngân hàng block chứ gì nữa mà ko biết..The payment was rejected, but we're not sure why
nice comment, btw fix quotation mark lol

2017-12-22 08:17 UTC, tetsureign requested changes
pls fix xd

2017-12-22 11:41 UTC, shortthu commented on resources/lang/vi/admin.php
> +                    'update' => 'Cập nhật',  // Update
no nvm haha, just keep it

2017-12-22 15:06 UTC, AcmeDVoid commented on resources/lang/vi/model_validation/fulfillments.php
> +        'insufficient_paid' => 'Không đủ tiền đổi tên tài khoản(:expected > :actual)', // Username change cost exceeds amount paid (:expected > :actual)
`chi phí vượt qua số tiền đã trả` tức là không đủ tiền rồi còn gì

2017-12-22 15:08 UTC, AcmeDVoid commented on resources/lang/vi/model_validation/fulfillments.php
> +        'only_one' => 'Bạn chỉ cho đổi tên tài khoản 1 lần cho mỗi đơn đặt hàng', //only 1 username change allowed per order fulfillment.
fixed

2017-12-22 15:09 UTC, shortthu commented on resources/lang/vi/model_validation/fulfillments.php
> +        'insufficient_paid' => 'Không đủ tiền đổi tên tài khoản(:expected > :actual)', // Username change cost exceeds amount paid (:expected > :actual)
à đọc lộn :)))) sorry

2017-12-22 15:11 UTC, AcmeDVoid commented on resources/lang/vi/model_validation/payments.php
> -            'virtual_only' => '`:provider` payment is not valid for physical items.',
fixed

2017-12-22 15:16 UTC, shortthu commented on resources/lang/vi/admin.php
> +                'store' => 'Cửa Hàng',  // Store
thế thì chỗ này viết hoa `Cửa` thôi :)))

2017-12-22 15:23 UTC, AcmeDVoid commented on resources/lang/vi/admin.php
> +                'store' => 'Cửa Hàng',  // Store
fixed

2017-12-23 07:13 UTC, shortthu commented on resources/lang/vi/admin.php
> +                    'update' => 'Cập Nhật',  // Update
sorry chỗ này cứ giữ nguyên như commit trước nhé 😛 mấy file kia shortthu cũng translate viết hoa đầu dòng thôi

2017-12-23 07:18 UTC, shortthu commented on resources/lang/vi/admin.php
> +                'no-cover' => 'Không có bộ bìa',  // No cover set
`Không có ảnh bìa` sẽ hay hơn

2017-12-23 07:38 UTC, shortthu commented on resources/lang/vi/model_validation/payments.php
> +        'user_id_mismatch' => 'chứa sai ID của người dùng',
ủa sao xóa `external_id` đi

2017-12-23 07:42 UTC, shortthu commented on resources/lang/vi/admin.php
>                      'default-topic' => 'Bìa chủ đề mặc định,'  // Default Topic Cover
cái này cũng viết hoa xd

2017-12-24 03:01 UTC, AcmeDVoid commented
Have to rollback.
Can't find the problem =(

2017-12-24 06:08 UTC, shortthu commented
Why close

2017-12-24 06:12 UTC, shortthu commented on resources/lang/vi/admin.php
> +            'title' => 'Đồ Chơi Điều Khiển của Quản Trị',
Giữ nguyên admin

2017-12-24 06:41 UTC, closed without merging