update 1 - 4 files
shortthu/osu-web pull request #4
Opened 2017-12-24 09:39 UTC by shortthu

(not 2 files like in the commit)

2017-12-24 17:27 UTC, adv3006 requested changes

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmap_discussions.php
> +            'false' => 'Bị mở lại bởi :user',
``Được`` nghe ổn hơn là ``Bị``

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +            'error' => 'Không thể lưu bài viết',
``Không thể lưu`` khác với ``Lưu thất bại`` nhé

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +        'title' => 'Cuộc Thảo Luận',
```Góc thảo luận``` nghe hay hơn

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +        'faves' => 'Yếu Thích',
Typo

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +        'approved' => 'Đã Approve',
``Được``

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +        'qualified' => 'Đã Qualify',
``Được``

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmaps.php
> +        'loved' => 'Đã Love',
``Được``

2017-12-24 17:27 UTC, adv3006 commented on resources/lang/vi/beatmap_discussions.php
> +            'true' => 'Được đánh dấu đã giải quyết bởi :user',
``Đã được giải quyết`` nghe thấy trôi chảy hơn

2017-12-24 17:27 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
>          'disqualifed-at' => 'Disqualified :time_ago (:reason).',
``Bị`` dq

2017-12-24 17:27 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +        'disqualifed_no_reason' => 'không đưa ra lí do',
``không có lý do cụ thể`` nghe ổn hơn

2017-12-24 17:27 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +        'ranked-approved' => 'Đã Rank & Approve',
``Được``

2017-12-24 20:33 UTC, Gagako commented on resources/lang/vi/beatmaps.php
> +        'title' => 'Cuộc Thảo Luận',
không hiểu tại sao title ở đây lại liên quan tới thảo luận

2017-12-24 20:35 UTC, Gagako commented on resources/lang/vi/beatmaps.php
> +        'approved' => 'Đã Approve',
sao mấy động từ này lại giữ nguyên mẫu nhỉ 🤔

2017-12-24 21:33 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +        'title' => 'Cuộc Thảo Luận',
Nguyên cái đó nằm trong key discussion lớn mà, ngay ở dòng 34 đó

2017-12-24 22:24 UTC, AcmeDVoid commented
File beatmap_discussions.php chưa pull trước đó mà đã dịch :S

2017-12-25 03:46 UTC, shortthu commented on resources/lang/vi/beatmap_discussions.php
> +            'false' => 'Bị mở lại bởi :user',
`Được mở lại` không thấy đúng lắm :thinking:

2017-12-25 03:46 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +            'error' => 'Không thể lưu bài viết',
👌

2017-12-25 04:01 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'title' => 'Cuộc Thảo Luận',
@Gagako cái này trong phần modding discussion á
@AcmeDVoid 👌

2017-12-25 04:01 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'disqualifed-at' => 'Disqualified :time_ago (:reason).',
👌

2017-12-25 04:02 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'disqualifed_no_reason' => 'không đưa ra lí do',
too long

2017-12-25 04:05 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'ranked-approved' => 'Đã Rank & Approve',
👌 , cả mấy cái dưới luôn :3

2017-12-25 04:06 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'approved' => 'Đã Approve',
"đã ranked" :thonk:

2017-12-25 04:06 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'faves' => 'Yếu Thích',
what typo tho

2017-12-25 04:07 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +        'faves' => 'Yếu Thích',
Yếu

2017-12-25 04:07 UTC, shortthu commented on resources/lang/vi/beatmaps.php
> +        'faves' => 'Yếu Thích',
ah, ok

2017-12-25 04:11 UTC, shortthu commented on resources/lang/vi/beatmap_discussions.php
> +            'true' => 'Được đánh dấu đã giải quyết bởi :user',
👌

2017-12-25 14:19 UTC, adv3006 reviewed
Should be good to go after this fix

2017-12-25 14:19 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +            'error' => 'Không thể cập nhật vote',
``Không thể`` khác với ``Failed``

2017-12-25 14:19 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
> +        'edited' => 'Sửa đổi cuối cùng bởi :editor :update_time.',
Use ``lần cuối`` instead of ``cuối cùng`` to avoid confusion

2017-12-25 17:55 UTC, adv3006 approved these changes

2017-12-25 18:01 UTC, merged