Update 3 - Beatmaps stuff
shortthu/osu-web pull request #8
Opened 2018-02-09 15:28 UTC by shortthu

👀

2018-02-12 01:55 UTC, adv3006 requested changes
Plz fix thanks

2018-02-12 01:55 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
Line 102???

2018-02-12 01:55 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
> +                'friend' => 'Chưa có bạn bèn nào của bạn lập điểm số tại beatmap này!',
*bạn bèn*

2018-02-12 01:55 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
> +                'unranked' => 'Beatmap chưa xếp hạng.',
Giữ nguyên từ thì tốt hơn

2018-02-12 01:55 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
>          'section_title' => 'Hype Train',
*Choo choo ~ just a random comment passing by*

2018-02-15 14:09 UTC, shortthu commented on resources/lang/vi/beatmapsets.php
> +                'friend' => 'Chưa có bạn bèn nào của bạn lập điểm số tại beatmap này!',
👍

2018-02-15 14:09 UTC, shortthu commented on resources/lang/vi/beatmapsets.php
> +                'unranked' => 'Beatmap chưa xếp hạng.',
đã dịch ranked tại sao không dịch unranked luôn

2018-02-15 14:10 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'section_title' => 'Hype Train',
:3c
uhhh so what's ur opinion now

2018-02-15 14:12 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
uhh what's wrong
*note:* chỗ này càng ngắn càng tốt nên không cho từ gốc vào

2018-02-15 16:24 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
dòng 102 đã có dịch rồi thì nên dịch nốt luôn
cuz *consistency* my dude xd

2018-02-15 16:24 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
> +                'unranked' => 'Beatmap chưa xếp hạng.',
Nghe thấy lạ

2018-02-16 09:45 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
ủa từ từ chấp nhận dịch rồi mà =))

2018-02-16 09:55 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
ủa mà line 102 là pending mà...?

2018-02-16 09:56 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
à không my bad looool

2018-02-16 09:58 UTC, shortthu commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
ok giờ thế này, cái line 102 là pending trong modding discussion dịch ra nó cũng không khớp với pending trong beatmapsets nên thôi giữ nguyên

2018-02-17 07:16 UTC, adv3006 requested changes
Need (at least) 1 more review

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmaps.php
>          'pending' => 'Pending',
Đang nói về việc dịch từ pending, chứ ko phải nói là 2 từ pending cùng nghĩa

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
> +                'rank' => 'Rank',
Chưa dịch

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'stars' => 'Star Difficulty',
Chưa dịch

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'ar' => 'Approach Rate',
Chưa dịch

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'accuracy' => 'Accuracy',
Chưa dịch

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'cs' => 'Circle Size',
Chưa dịch

2018-02-17 07:16 UTC, AcmeDVoid commented on resources/lang/vi/beatmapset_watches.php
> +            'empty' => 'Bạn chưa theo dõi cuộc thảo luận nào.',
Thừa chữ *bạn*

2018-02-17 10:10 UTC, shortthu commented on resources/lang/vi/beatmapsets.php
>              'cs' => 'Circle Size',
đây và mấy cái trên là thuật ngữ mọi người đã sử dụng rất nhiều nên không dịch tốt hơn
dịch ra cũng chuối lắm :))))

2018-02-17 10:11 UTC, shortthu commented on resources/lang/vi/beatmapset_watches.php
> +            'empty' => 'Bạn chưa theo dõi cuộc thảo luận nào.',
intentional, more user-friendly

2018-02-17 10:14 UTC, shortthu commented on resources/lang/vi/beatmapset_watches.php
> +            'empty' => 'Bạn chưa theo dõi cuộc thảo luận nào.',
mà thôi dịch như văn bản gốc tốt hơn :))))

2018-02-17 16:45 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'cs' => 'Circle Size',
vậy còn *người mới*?

2018-02-17 17:07 UTC, shortthu commented
stop memeing on this stuff please
also can i just reply "cuz i like that"

-----Thư Gốc-----
Từ: "adv3006" <notifications@github.com>
Gửi: ‎17/‎02/‎2018 23:45
Đến: "shortthu/osu-web" <osu-web@noreply.github.com>
Cc: "Thiên Thư" <thuthien2001@gmail.com>; "Author" <author@noreply.github.com>
Chủ đề: Re: [shortthu/osu-web] Update 3 - Beatmaps stuff (#8)

@AcmeDVoid commented on this pull request.



In resources/lang/vi/beatmapsets.php:
>                  'direct' => 'osu!direct',
             ],
-            'favourite' => 'Favourite this beatmapset',
-            'unfavourite' => 'Unfavourite this beatmapset',
-            'favourited_count' => '+ 1 other!|+ :count others!',
+            'favourite' => 'Yêu thích beatmapset này',
+            'unfavourite' => 'Bỏ yêu thích beatmapset này',
+            'favourited_count' => '+ :count nữa!',
         ],
         'stats' => [
             'cs' => 'Circle Size',
vậy còn người mới?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-02-22 04:56 UTC, adv3006 reviewed
Last* review

2018-02-22 04:56 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'accuracy' => 'Accuracy',
.

2018-02-22 04:56 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'ar' => 'Approach Rate',
.

2018-02-22 04:56 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'stars' => 'Star Difficulty',
.

2018-02-22 04:56 UTC, AcmeDVoid commented on resources/lang/vi/beatmapsets.php
>              'count_circles' => 'Circle Count',
Chưa dịch

2018-02-22 05:00 UTC, shortthu commented
wish I can buy you a new glasses :^)

2018-02-22 05:01 UTC, AcmeDVoid commented
rip

2018-02-22 05:02 UTC, adv3006 approved these changes

2018-02-22 05:02 UTC, merged